version: "3"
services:
  client:
    build: ./client
    container_name: ecommerce_client
    stdin_open: true
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
