version: "3"
services:
  client:
    build: ./client
    container_name: ecommerce_client
    stdin_open: true
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules

  usersDb:
    image: mongo:latest
    container_name: ecommerce_user_db
    ports:
      - "27018:27017"
    volumes:
      - users-volume:/data/db

  user_service:
    build: ./userService
    container_name: ecommerce_user_service
    stdin_open: true
    ports:
      - "5001:5001"
    links:
      - usersDb
    depends_on:
      - usersDb
    volumes:
      - ./userService:/app
      - /app/node_modules

  categoryservice:
    build: ./categoryservice
    container_name: categories_container
    stdin_open: true
    ports:
      - "5003:5003"
    networks:
      - my-app
    links:
      - category_db
    restart: on-failure
    depends_on:
      - category_db
    volumes:
      - ./categoryservice:/app
      - /app/__pycache__

  category_db:
    image: mysql:latest
    ports:
      - "3306:3306"
    networks:
      - my-app
    volumes:
      - category-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: category_database
volumes:
  users-volume:
    driver: local
  category-volume:
    driver: local

networks:
  my-app:
    driver: bridge