version: "3"
services:
  client:
    build: ./client
    container_name: ecommerce_client
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      - e-commerce-app
    volumes:
      - ./client:/app
      - /app/node_modules

  auth-service:
    build: ./authService
    container_name: ecommerce_auth_service
    stdin_open: true
    ports:
      - "5000:5000"
    networks:
      - e-commerce-app
    links:
      - auth-db
    restart: on-failure
    depends_on:
      - auth-db
    volumes:
      - ./authService:/app
      - /app/node_modules

  auth-db:
    image: mongo:latest
    container_name: ecommerce_user_auth_db
    ports:
      - "27020:27017"
    networks:
      - e-commerce-app
    volumes:
      - auth-volume:/data/db

  usersDb:
    image: mongo:latest
    container_name: ecommerce_user_db
    ports:
      - "27018:27017"
    networks:
      - e-commerce-app
    volumes:
      - users-volume:/data/db

  user-service:
    build: ./userService
    container_name: ecommerce_user_service
    stdin_open: true
    ports:
      - "5001:5001"
    networks:
      - e-commerce-app
    links:
      - usersDb
    depends_on:
      - usersDb
    volumes:
      - ./userService:/app
      - /app/node_modules

  categoryservice:
    build: ./categoryService
    container_name: categories_container
    stdin_open: true
    ports:
      - "5003:5003"
    networks:
      - e-commerce-app
    links:
      - category_db
    restart: on-failure
    depends_on:
      - category_db
    volumes:
      - ./categoryServices:/app
      - /app/__pycache__

  category_db:
    image: mysql:latest
    ports:
      - "3306:3306"
    networks:
      - e-commerce-app
    volumes:
      - category-volume:/var/lib/mysql
    environment:
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: category_database

networks:
  e-commerce-app:
    driver: bridge
volumes:
  auth-volume:
    driver: local
  users-volume:
    driver: local
  category-volume:
    driver: local
