openapi: '3.0.2'
info:
  title: User Service
  version: '1.0'
  description: User Service API Documentation of e-commerce app
tags:
  - name: User
    description: ''

servers:
  - url: http://localhost:5001/

paths:
  /user:
    post:
      tags:
        - User
      description: add User api
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/addUserRequest"
      responses:
        '201':
          description: Created succesfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/addUserResponse'
        '403':
          $ref: '#/components/responses/usernameExist'
        '400':
          $ref: '#/components/responses/validation'
          

components:
  schemas:
    addUserRequest:
      type: object
      properties:
        name:
          type: string
          example: Kirollos rafik
        email: 
          type: string
          example: k@gmail.com
        usrname:
          type: string
          example: k123
        phone:
          type: string
          example: 01234567890
        address:
          type: string
          example: 17 mohamed street
    addUserResponse:
      type: object
      properties:
        success:
          type: boolean
          example: true
        id:
          type: string
          example: 662ec00131ad8002c77c734a
        message:
          type: string
          example: User created!
    validationArray:
      type: object
      properties:
        type: 
          type: string
          example: field
        value:
          type: string
          example: 0123456789
        msg:
          type: string
          example: Phone number must be in the format 01xxxxxxxxx"
        path:
          type: string
          example: phone
        location:
          type: string
          example: body

  responses:
    usernameExist:
      description: Username already exist
      content:
        application/json:
          schema:
            type: object
            properties:
              success: 
                type: boolean
                example: false
              error:
                type: string
                example: Username already exists
    validation:
      description: ''
      content:
        application/json:
          schema: 
            type: object
            properties:
              errors:
                type: array
                items:
                  $ref: '#/components/schemas/validationArray'

  
          


          

 